version: '3'

services:
  app:
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
        - db
    container_name: dev_test_app

  db:
      image: mysql:8.3
      restart: always
      volumes:
          - ./tmp/db:/var/lib/mysql
      environment:
          MYSQL_DATABASE: dev_test
          MYSQL_ROOT_PASSWORD: root
      ports:
          - "8101:3306"
      command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
      container_name: dev_test_db
